import { db } from '@/db';
import { content } from '@/db/schema';

async function main() {
    const sampleContent = [
        // Movies
        {
            title: 'Black Panther',
            description: 'After the death of his father, T\'Challa returns home to the African nation of Wakanda to take his rightful place as king. When a powerful enemy suddenly reappears, T\'Challa\'s mettle as king and as Black Panther gets tested.',
            type: 'movie',
            genre: ['Action', 'Adventure', 'Sci-Fi'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=xjDjIWPwcPU',
            videoUrl: 'https://www.youtube.com/watch?v=dxWvtMOGAhw',
            subtitleUrls: { en: 'https://example.com/subs/black-panther-en.vtt', es: 'https://example.com/subs/black-panther-es.vtt' },
            tmdbId: 284054,
            releaseDate: '2018-02-16',
            duration: 134,
            status: 'published',
            viewCount: 45230,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'John Wick',
            description: 'An ex-hit-man comes out of retirement to track down the gangsters that took everything from him. With New York City as his bullet-riddled playground, John Wick embarks on a merciless rampage.',
            type: 'movie',
            genre: ['Action', 'Thriller', 'Crime'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=C0BMx-qxsP4',
            videoUrl: 'https://www.youtube.com/watch?v=2AUmvWm5ZDQ',
            subtitleUrls: { en: 'https://example.com/subs/john-wick-en.vtt', fr: 'https://example.com/subs/john-wick-fr.vtt' },
            tmdbId: 245891,
            releaseDate: '2014-10-24',
            duration: 101,
            status: 'published',
            viewCount: 38950,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            title: 'Mad Max: Fury Road',
            description: 'An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken. Within this world exist two rebels on the run who just might be able to restore order.',
            type: 'movie',
            genre: ['Action', 'Adventure', 'Sci-Fi'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=hEJnMQG9ev8',
            videoUrl: 'https://www.youtube.com/watch?v=YWNWi-ZWL3c',
            subtitleUrls: { en: 'https://example.com/subs/mad-max-en.vtt', es: 'https://example.com/subs/mad-max-es.vtt' },
            tmdbId: 76341,
            releaseDate: '2015-05-15',
            duration: 120,
            status: 'published',
            viewCount: 42180,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            title: 'The Shawshank Redemption',
            description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. This timeless story of hope and friendship transcends the confines of prison walls.',
            type: 'movie',
            genre: ['Drama'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=6hB3S9bIaco',
            videoUrl: 'https://www.youtube.com/watch?v=NmzuHjWmXOc',
            subtitleUrls: { en: 'https://example.com/subs/shawshank-en.vtt', fr: 'https://example.com/subs/shawshank-fr.vtt' },
            tmdbId: 278,
            releaseDate: '1994-09-23',
            duration: 142,
            status: 'published',
            viewCount: 52340,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            title: 'Forrest Gump',
            description: 'The presidencies of Kennedy and Johnson, Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75. His extraordinary journey through life touches the hearts of millions.',
            type: 'movie',
            genre: ['Drama', 'Comedy'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
            videoUrl: 'https://www.youtube.com/watch?v=XHhAG-YLdk8',
            subtitleUrls: { en: 'https://example.com/subs/forrest-gump-en.vtt', es: 'https://example.com/subs/forrest-gump-es.vtt' },
            tmdbId: 13,
            releaseDate: '1994-07-06',
            duration: 142,
            status: 'published',
            viewCount: 48765,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            title: 'The Grand Budapest Hotel',
            description: 'The adventures of Gustave H, a legendary concierge at a famous European hotel, and his protégé Zero Moustafa. The story involves the theft of a priceless painting and a family fortune.',
            type: 'movie',
            genre: ['Comedy', 'Drama'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=1Fg5iWmQjwk',
            videoUrl: 'https://www.youtube.com/watch?v=_eUwdmfBRSY',
            subtitleUrls: { en: 'https://example.com/subs/budapest-en.vtt', fr: 'https://example.com/subs/budapest-fr.vtt' },
            tmdbId: 120467,
            releaseDate: '2014-03-28',
            duration: 99,
            status: 'draft',
            viewCount: 15420,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            title: 'Blade Runner 2049',
            description: 'Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what\'s left of society into chaos.',
            type: 'movie',
            genre: ['Sci-Fi', 'Drama', 'Thriller'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=gCcx85zbxz4',
            videoUrl: 'https://www.youtube.com/watch?v=dZOaI_R8ZhM',
            subtitleUrls: { en: 'https://example.com/subs/blade-runner-en.vtt', es: 'https://example.com/subs/blade-runner-es.vtt' },
            tmdbId: 335984,
            releaseDate: '2017-10-06',
            duration: 164,
            status: 'published',
            viewCount: 35670,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        // TV Shows
        {
            title: 'Breaking Bad',
            description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future. What starts as a desperate act becomes a thrilling journey into the criminal underworld.',
            type: 'tv',
            genre: ['Drama', 'Crime', 'Thriller'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=HhesaQXLuRY',
            videoUrl: 'https://www.youtube.com/watch?v=ceqOTZnhgp8',
            subtitleUrls: { en: 'https://example.com/subs/breaking-bad-en.vtt', es: 'https://example.com/subs/breaking-bad-es.vtt' },
            tmdbId: 1396,
            releaseDate: '2008-01-20',
            duration: 47,
            status: 'published',
            viewCount: 67890,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            title: 'The Crown',
            description: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century. An intimate portrait of the British royal family across decades.',
            type: 'tv',
            genre: ['Drama', 'Biography', 'History'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/1M876KPjulVwppEpldhdc8V4o68.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=JWtnJjn6ng0',
            videoUrl: 'https://www.youtube.com/watch?v=UukVpYmxvLE',
            subtitleUrls: { en: 'https://example.com/subs/crown-en.vtt', fr: 'https://example.com/subs/crown-fr.vtt' },
            tmdbId: 1399,
            releaseDate: '2016-11-04',
            duration: 58,
            status: 'published',
            viewCount: 43210,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            title: 'Stranger Things',
            description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl. Set in the 1980s, this series blends supernatural horror with nostalgic charm.',
            type: 'tv',
            genre: ['Drama', 'Fantasy', 'Horror'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=b9EkMc79ZSU',
            videoUrl: 'https://www.youtube.com/watch?v=XWxyRG_tckY',
            subtitleUrls: { en: 'https://example.com/subs/stranger-things-en.vtt', es: 'https://example.com/subs/stranger-things-es.vtt' },
            tmdbId: 66732,
            releaseDate: '2016-07-15',
            duration: 51,
            status: 'published',
            viewCount: 58940,
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            title: 'The Office',
            description: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium. Steve Carell stars as the bumbling regional manager Michael Scott.',
            type: 'tv',
            genre: ['Comedy'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=LHOtME2DL4g',
            videoUrl: 'https://www.youtube.com/watch?v=Q8pNh6LqFh8',
            subtitleUrls: { en: 'https://example.com/subs/office-en.vtt', fr: 'https://example.com/subs/office-fr.vtt' },
            tmdbId: 2316,
            releaseDate: '2005-03-24',
            duration: 22,
            status: 'published',
            viewCount: 72150,
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            title: 'Brooklyn Nine-Nine',
            description: 'Comedy series following the exploits of Det. Jake Peralta and his diverse, lovable colleagues as they police the NYPD\'s 99th Precinct. A workplace comedy that balances humor with heart and tackles social issues.',
            type: 'tv',
            genre: ['Comedy', 'Crime'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/hgRMSOt7a1b8qyQR68vUixJPang.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/hgRMSOt7a1b8qyQR68vUixJPang.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=sJzHojBUJc8',
            videoUrl: 'https://www.youtube.com/watch?v=D1z1SLoWOxA',
            subtitleUrls: { en: 'https://example.com/subs/brooklyn-en.vtt', es: 'https://example.com/subs/brooklyn-es.vtt' },
            tmdbId: 48891,
            releaseDate: '2013-09-17',
            duration: 21,
            status: 'draft',
            viewCount: 12560,
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        {
            title: 'Black Mirror',
            description: 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide. Each standalone episode examines modern society and technology through a dark, satirical lens.',
            type: 'tv',
            genre: ['Sci-Fi', 'Thriller', 'Drama'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/5UaYsGZOFhjFDwQh6GuLjjA5WSpO.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/5UaYsGZOFhjFDwQh6GuLjjA5WSpO.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=jROLrhQkK78',
            videoUrl: 'https://www.youtube.com/watch?v=V0XOApF5nLU',
            subtitleUrls: { en: 'https://example.com/subs/black-mirror-en.vtt', fr: 'https://example.com/subs/black-mirror-fr.vtt' },
            tmdbId: 42009,
            releaseDate: '2011-12-04',
            duration: 60,
            status: 'published',
            viewCount: 39840,
            createdAt: new Date('2024-03-25').toISOString(),
            updatedAt: new Date('2024-03-25').toISOString(),
        },
        {
            title: 'Westworld',
            description: 'A dark odyssey about the dawn of artificial consciousness and the evolution of sin, exploring a world in which every human appetite can be indulged. Set in a futuristic theme park populated by android hosts.',
            type: 'tv',
            genre: ['Sci-Fi', 'Drama', 'Western'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/y55oBgf6bVMnqJ6rMbOKdRnpKOZ.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/y55oBgf6bVMnqJ6rMbOKdRnpKOZ.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=eX3u0IlBBO4',
            videoUrl: 'https://www.youtube.com/watch?v=sjVqDg32_8s',
            subtitleUrls: { en: 'https://example.com/subs/westworld-en.vtt', es: 'https://example.com/subs/westworld-es.vtt' },
            tmdbId: 63247,
            releaseDate: '2016-10-02',
            duration: 62,
            status: 'published',
            viewCount: 28750,
            createdAt: new Date('2024-04-01').toISOString(),
            updatedAt: new Date('2024-04-01').toISOString(),
        },
        {
            title: 'Game of Thrones',
            description: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia. Based on George R.R. Martin\'s epic fantasy series, this show redefined television drama.',
            type: 'tv',
            genre: ['Action', 'Adventure', 'Drama'],
            language: 'en',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
            posterUrl: 'https://image.tmdb.org/t/p/w780/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
            trailerUrl: 'https://www.youtube.com/watch?v=rlR4PJn8b8I',
            videoUrl: 'https://www.youtube.com/watch?v=BpJYNVhGf1s',
            subtitleUrls: { en: 'https://example.com/subs/got-en.vtt', fr: 'https://example.com/subs/got-fr.vtt', es: 'https://example.com/subs/got-es.vtt' },
            tmdbId: 1399,
            releaseDate: '2011-04-17',
            duration: 57,
            status: 'published',
            viewCount: 89540,
            createdAt: new Date('2024-04-05').toISOString(),
            updatedAt: new Date('2024-04-05').toISOString(),
        }
    ];

    await db.insert(content).values(sampleContent);
    
    console.log('✅ Content seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});