import { db } from '@/db';
import { watchHistory } from '@/db/schema';

async function main() {
    const now = Math.floor(Date.now() / 1000);
    const dayInSeconds = 24 * 60 * 60;

    const sampleWatchHistory = [
        // Day 1 (today)
        {
            userId: 'user_1',
            contentId: 'deathnote_123',
            contentType: 'tv',
            title: 'Death Note',
            posterPath: 'https://image.tmdb.org/t/p/w500/deathnote.jpg',
            watchedAt: now - (3 * 3600),
            progressSeconds: 1380,
            totalSeconds: 1380,
        },
        {
            userId: 'user_2',
            contentId: 'yourname_456',
            contentType: 'movie',
            title: 'Your Name',
            posterPath: 'https://image.tmdb.org/t/p/w500/yourname.jpg',
            watchedAt: now - (3.5 * 3600),
            progressSeconds: 6480,
            totalSeconds: 6480,
        },
        {
            userId: 'user_3',
            contentId: 'aot_789',
            contentType: 'tv',
            title: 'Attack on Titan',
            posterPath: 'https://image.tmdb.org/t/p/w500/aot.jpg',
            watchedAt: now - (5 * 3600),
            progressSeconds: 1440,
            totalSeconds: 1440,
        },
        // Day 2 (yesterday)
        {
            userId: 'user_1',
            contentId: 'naruto_234',
            contentType: 'tv',
            title: 'Naruto',
            posterPath: 'https://image.tmdb.org/t/p/w500/naruto.jpg',
            watchedAt: now - dayInSeconds - (2 * 3600),
            progressSeconds: 1380,
            totalSeconds: 1380,
        },
        {
            userId: 'user_4',
            contentId: 'demonslayer_567',
            contentType: 'tv',
            title: 'Demon Slayer',
            posterPath: 'https://image.tmdb.org/t/p/w500/demonslayer.jpg',
            watchedAt: now - dayInSeconds - (2.5 * 3600),
            progressSeconds: 1440,
            totalSeconds: 1440,
        },
        {
            userId: 'user_2',
            contentId: 'onepiece_890',
            contentType: 'tv',
            title: 'One Piece',
            posterPath: 'https://image.tmdb.org/t/p/w500/onepiece.jpg',
            watchedAt: now - dayInSeconds - (4 * 3600),
            progressSeconds: 1380,
            totalSeconds: 1380,
        },
        // Day 3 (2 days ago)
        {
            userId: 'user_3',
            contentId: 'spiritedaway_345',
            contentType: 'movie',
            title: 'Spirited Away',
            posterPath: 'https://image.tmdb.org/t/p/w500/spiritedaway.jpg',
            watchedAt: now - (2 * dayInSeconds) - (1.5 * 3600),
            progressSeconds: 7440,
            totalSeconds: 7440,
        },
        {
            userId: 'user_5',
            contentId: 'mha_678',
            contentType: 'tv',
            title: 'My Hero Academia',
            posterPath: null,
            watchedAt: now - (2 * dayInSeconds) - (3 * 3600),
            progressSeconds: 1380,
            totalSeconds: 1380,
        },
        {
            userId: 'user_1',
            contentId: 'fma_901',
            contentType: 'tv',
            title: 'Fullmetal Alchemist',
            posterPath: 'https://image.tmdb.org/t/p/w500/fma.jpg',
            watchedAt: now - (2 * dayInSeconds) - (4.5 * 3600),
            progressSeconds: 1440,
            totalSeconds: 1440,
        },
        // Day 4 (3 days ago)
        {
            userId: 'user_4',
            contentId: 'weathering_456',
            contentType: 'movie',
            title: 'Weathering with You',
            posterPath: 'https://image.tmdb.org/t/p/w500/weathering.jpg',
            watchedAt: now - (3 * dayInSeconds) - (1 * 3600),
            progressSeconds: 6780,
            totalSeconds: 6780,
        },
        {
            userId: 'user_2',
            contentId: 'sao_789',
            contentType: 'tv',
            title: 'Sword Art Online',
            posterPath: 'https://image.tmdb.org/t/p/w500/sao.jpg',
            watchedAt: now - (3 * dayInSeconds) - (2 * 3600),
            progressSeconds: 1380,
            totalSeconds: 1380,
        },
        {
            userId: 'user_6',
            contentId: 'tokyoghoul_012',
            contentType: 'tv',
            title: 'Tokyo Ghoul',
            posterPath: null,
            watchedAt: now - (3 * dayInSeconds) - (3.5 * 3600),
            progressSeconds: 1440,
            totalSeconds: 1440,
        },
        {
            userId: 'user_1',
            contentId: 'vinlandsaga_345',
            contentType: 'tv',
            title: 'Vinland Saga',
            posterPath: 'https://image.tmdb.org/t/p/w500/vinland.jpg',
            watchedAt: now - (3 * dayInSeconds) - (5 * 3600),
            progressSeconds: 900,
            totalSeconds: 1440,
        },
        // Day 5 (4 days ago)
        {
            userId: 'user_3',
            contentId: 'mononoke_567',
            contentType: 'movie',
            title: 'Princess Mononoke',
            posterPath: 'https://image.tmdb.org/t/p/w500/mononoke.jpg',
            watchedAt: now - (4 * dayInSeconds) - (3 * 3600),
            progressSeconds: 8040,
            totalSeconds: 8040,
        },
        {
            userId: 'user_7',
            contentId: 'hxh_890',
            contentType: 'tv',
            title: 'Hunter x Hunter',
            posterPath: 'https://image.tmdb.org/t/p/w500/hxh.jpg',
            watchedAt: now - (4 * dayInSeconds) - (1.5 * 3600),
            progressSeconds: 1380,
            totalSeconds: 1380,
        },
        {
            userId: 'user_1',
            contentId: 'steinsgate_123',
            contentType: 'tv',
            title: 'Steins;Gate',
            posterPath: 'https://image.tmdb.org/t/p/w500/steinsgate.jpg',
            watchedAt: now - (4 * dayInSeconds) - (5 * 3600),
            progressSeconds: 1440,
            totalSeconds: 1440,
        },
        {
            userId: 'user_2',
            contentId: 'gardenwords_678',
            contentType: 'movie',
            title: 'The Garden of Words',
            posterPath: 'https://image.tmdb.org/t/p/w500/garden.jpg',
            watchedAt: now - (4 * dayInSeconds) - (6 * 3600),
            progressSeconds: 2700,
            totalSeconds: 2760,
        },
        // Day 6 (5 days ago)
        {
            userId: 'user_5',
            contentId: 'silentvoice_234',
            contentType: 'movie',
            title: 'A Silent Voice',
            posterPath: 'https://image.tmdb.org/t/p/w500/silentvoice.jpg',
            watchedAt: now - (5 * dayInSeconds) - (2 * 3600),
            progressSeconds: 7740,
            totalSeconds: 7740,
        },
        {
            userId: 'user_2',
            contentId: 'jjk_567',
            contentType: 'tv',
            title: 'Jujutsu Kaisen',
            posterPath: 'https://image.tmdb.org/t/p/w500/jjk.jpg',
            watchedAt: now - (5 * dayInSeconds) - (2.5 * 3600),
            progressSeconds: 1380,
            totalSeconds: 1380,
        },
        {
            userId: 'user_4',
            contentId: 'codegeass_890',
            contentType: 'tv',
            title: 'Code Geass',
            posterPath: null,
            watchedAt: now - (5 * dayInSeconds) - (4 * 3600),
            progressSeconds: 1440,
            totalSeconds: 1440,
        },
        {
            userId: 'user_5',
            contentId: 'violetever_901',
            contentType: 'tv',
            title: 'Violet Evergarden',
            posterPath: 'https://image.tmdb.org/t/p/w500/violet.jpg',
            watchedAt: now - (5 * dayInSeconds) - (6 * 3600),
            progressSeconds: 720,
            totalSeconds: 1380,
        },
        // Day 7 (6 days ago)
        {
            userId: 'user_6',
            contentId: 'howl_123',
            contentType: 'movie',
            title: "Howl's Moving Castle",
            posterPath: 'https://image.tmdb.org/t/p/w500/howl.jpg',
            watchedAt: now - (6 * dayInSeconds) - (1 * 3600),
            progressSeconds: 7080,
            totalSeconds: 7080,
        },
        {
            userId: 'user_3',
            contentId: 'mobpsycho_456',
            contentType: 'tv',
            title: 'Mob Psycho 100',
            posterPath: 'https://image.tmdb.org/t/p/w500/mobpsycho.jpg',
            watchedAt: now - (6 * dayInSeconds) - (2 * 3600),
            progressSeconds: 1380,
            totalSeconds: 1380,
        },
        {
            userId: 'user_7',
            contentId: 'bebop_789',
            contentType: 'tv',
            title: 'Cowboy Bebop',
            posterPath: 'https://image.tmdb.org/t/p/w500/bebop.jpg',
            watchedAt: now - (6 * dayInSeconds) - (3 * 3600),
            progressSeconds: 1440,
            totalSeconds: 1440,
        },
        {
            userId: 'user_4',
            contentId: 'castle_012',
            contentType: 'movie',
            title: 'Castle in the Sky',
            posterPath: 'https://image.tmdb.org/t/p/w500/castle.jpg',
            watchedAt: now - (6 * dayInSeconds) - (4 * 3600),
            progressSeconds: 3600,
            totalSeconds: 7440,
        },
    ];

    await db.insert(watchHistory).values(sampleWatchHistory);
    
    console.log('✅ Watch history seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});